name: ieai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - pyzmq
  - ncurses
  - openssl
  - readline
  - setuptools
  - tk
  - tornado
  - traitlets
  - wheel
  - typing_extensions
  - pip:
      - absl-py
      - accelerate
      - albumentations
      - annotated-types
      - beartype
      - beautifulsoup4
      - circuitsvis
      - datasets
      - diffusers
      - dill
      - dlib
      - einops
      - face-recognition
      - face-recognition-models
      - fancy-einsum
      - filelock
      - ftfy
      - gdown
      - gplearn
      - grpcio
      - hf-xet
      - huggingface-hub
      - imageio
      - importlib-metadata
      - jaxtyping
      - jinja2
      - joblib
      - jsonschema
      - juliacall
      - juliapkg
      - lazy-loader
      - lit
      - littleutils
      - ltntorch
      - markdown
      - markdown-it-py
      - matplotlib
      - mdurl
      - mpmath
      - networkx
      - nltk
      - opencv-python
      - opencv-python-headless
      - outdated
      - packaging
      - pillow
      - plotly
      - propcache
      - protobuf
      - psutil
      - pyarrow
      - pydantic
      - pygments
      - pyparsing
      - pysocks
      - pysr
      - python-dateutil
      - pytz
      - pyyaml
      - regex
      - requests
      - rich
      - safetensors
      - scikit-image
      - sentencepiece
      - sentry-sdk
      - setproctitle
      - simsimd
      - six
      - soupsieve
      - stringzilla
      - sympy
      - tabulate
      - tensorboard-data-server
      - tb-nightly
      - threadpoolctl
      - tifffile
      - timm
      - tokenizers
      - torch==2.7.1+cu128
      - torchaudio==2.7.1+cu128
      - torchvision==0.22.1+cu128
      - torchinfo
      - torchsummary
      - transformer-lens==2.16.1
      - transformers
      - transformers-stream-generator
      - triton
      - typeguard
      - typing-inspection
      - urllib3
      - wandb
      - wcwidth
      - werkzeug
      - wilds
      - xxhash
      - yacs
      - yapf
      - yarl
      - zipp
      - kaleido
